[package]
name = "moonshine-save"
version = "0.3.7"
edition = "2021"
license = "MIT"
description = "Save/Load framework for Bevy"
categories = ["game-development"]
keywords = ["bevy", "save", "load", "serde", "ron"]
readme = "README.md"
homepage = "https://github.com/Zeenobit/moonshine_save"
repository = "https://github.com/Zeenobit/moonshine_save"

[dependencies]
ron = "0.8.0"
serde = "1.0.*"
bevy_app = "0.13.*"
bevy_ecs = "0.13.*"
bevy_hierarchy = "0.13.*"
bevy_reflect = "0.13.*"
bevy_scene = "0.13.*"
bevy_utils = "0.13.*"
moonshine-util = { version = "0.2.0", path = "../util" }

[dev-dependencies]
bevy = "0.13.*"
